apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pp2v6emm7-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pp2v6emm7-nodejs 
  name: pp2v6emm7-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: pp2v6emm7-nodejs 
